spring:
  application:
    name: rate-limit

  redis:
    host: 192.168.10.140
    password: 123456
    port: 6379
    database: 3
    timeout: 5000
    redisson:
      connectionMinimumIdleSize: 1
  lock:
    error-msg: "'等待超过'+#waitTime+'秒，系统繁忙，请稍后再试。'"